# Generated by Django 5.1.4 on 2024-12-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_nl', models.CharField(max_length=255, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('text_nl', models.TextField(null=True)),
            ],
        ),
    ]
