# Generated by Django 5.1.4 on 2024-12-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMainApp', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('childFirstName', models.CharField(max_length=50)),
                ('childLastName', models.CharField(max_length=50)),
                ('childAge', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='purpose',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
