# Generated by Django 4.2.17 on 2025-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMainApp', '0005_subject_title_en_subject_title_nl_subject_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/'),
        ),
    ]
