# Generated by Django 4.2.17 on 2025-01-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMainApp', '0006_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='long_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
