# Generated by Django 4.2.17 on 2025-01-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolMainApp', '0007_subject_long_description_subject_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='long_description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='long_description_nl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='long_description_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_description_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_description_nl',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='short_description_ru',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
